name: databricks-push-repo
description: Push a branch to Databricks Repos. If the repo doesn't exist, create it first.

inputs:
  host:
    description: Databricks host
    required: true
  token:
    description: Databricks API token
    required: true
  path:
    description: Target repo path on Databricks
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - run: |
        python -m pip install --upgrade pip wheel
        python -m pip install -r "${GITHUB_ACTION_PATH}/requirements.txt"
      shell: bash
    - run: |
        python "${GITHUB_ACTION_PATH}/push_repo.py" --url "https://github.com/${GITHUB_REPOSITORY}" --branch "${GITHUB_REF}" \
          --host ${{ inputs.host }} --token ${{ inputs.token }} --path ${{ inputs.path }}
      shell: bash
